from sqlmodel import Session, select

from app.models.business_document import QuotationDocument
from app.models.inventory_item import InventoryItem
from app.services.business_document_service import sync_business_documents
from app.services.chat_handlers.common import (
    HandlerResult,
    format_number,
    row_citation,
    source_dict,
)
from app.services.inventory_service import sync_inventory_items
from app.services.purchase_recommendation_service import list_required_order_items


def _ensure_inventory_loaded(session: Session, repository_id: str) -> None:
    exists = session.exec(
        select(InventoryItem.id).where(InventoryItem.repository_id == repository_id)
    ).first()
    if exists:
        return

    try:
        sync_inventory_items(session, repository_id)
    except ValueError:
        return


def _ensure_business_documents_loaded(session: Session, repository_id: str) -> None:
    exists = session.exec(
        select(QuotationDocument.id).where(QuotationDocument.repository_id == repository_id)
    ).first()
    if exists:
        return

    try:
        sync_business_documents(session, repository_id)
    except ValueError:
        return


def _remaining_quantity(item: InventoryItem) -> float:
    if item.current_remaining_quantity is not None:
        return item.current_remaining_quantity
    return item.current_stock


def _shortage_quantity(item: InventoryItem) -> float:
    remaining = _remaining_quantity(item)
    if item.target_stock is not None:
        return max(item.target_stock - remaining, 0)
    if item.safety_stock is not None:
        return max(item.safety_stock - remaining, 0)
    return 0


def _is_shortage_item(item: InventoryItem) -> bool:
    if _shortage_quantity(item) > 0:
        return True
    if item.stock_status and "부족" in item.stock_status:
        return True
    return False


def _asks_deadline(message: str) -> bool:
    return any(keyword in message for keyword in ["내일", "내일까지", "오늘", "이번 주"])


def handle_purchase_required_query(
    session: Session,
    repository_id: str,
    message: str,
) -> HandlerResult:
    # Purchase recommendations are computed from structured demo tables, not
    # generated by the LLM. This keeps the answer explainable during demos.
    _ensure_inventory_loaded(session, repository_id)
    _ensure_business_documents_loaded(session, repository_id)

    inventory_items = session.exec(
        select(InventoryItem)
        .where(InventoryItem.repository_id == repository_id)
        .order_by(InventoryItem.item_name.asc())
    ).all()
    shortage_items = [item for item in inventory_items if _is_shortage_item(item)]
    shortage_items.sort(key=lambda item: _shortage_quantity(item), reverse=True)

    try:
        required_order_items = list_required_order_items(session, repository_id)
    except ValueError:
        required_order_items = []

    if not shortage_items and not required_order_items:
        return HandlerResult(
            answer=(
                "현재 등록된 재고현황과 견적서 기준으로 발주가 필요한 품목은 확인되지 않습니다."
            ),
            sources=[],
        )

    lines: list[str] = []
    if _asks_deadline(message):
        lines.append(
            "내일까지 발주 여부는 별도 발주 마감일 필드가 없어 정확한 날짜 기준으로는 판단이 제한됩니다."
        )
        lines.append("대신 현재 재고현황과 견적서 기준의 발주 필요 후보를 확인했습니다.")
    else:
        lines.append("현재 데이터 기준 발주 필요 후보입니다.")

    sources: list[dict] = []

    if shortage_items:
        lines.append("")
        lines.append(f"재고 부족 기준 발주 후보 {len(shortage_items)}건")
        for item in shortage_items[:10]:
            remaining = _remaining_quantity(item)
            shortage = _shortage_quantity(item)
            unit = item.unit or "개"
            target = item.target_stock if item.target_stock is not None else item.safety_stock
            lines.append(
                "- "
                f"{item.item_name}({item.item_code}): 잔여 {format_number(remaining)}{unit}, "
                f"기준 {format_number(target)}{unit}, "
                f"부족 {format_number(shortage)}{unit}, "
                f"공급사 {item.supplier or '-'}"
            )
            citation = row_citation(item.source_filename, item.source_sheet_name, item.source_row)
            sources.append(
                source_dict(
                    source_type="inventory",
                    filename=item.source_filename,
                    row=item.source_row,
                    citation=citation,
                    text=(
                        f"품목명={item.item_name}, 품목코드={item.item_code}, "
                        f"잔여수량={remaining}, 목표/안전재고={target}, 부족수량={shortage}"
                    ),
                )
            )

    if required_order_items:
        lines.append("")
        lines.append(f"견적서에는 있으나 재고현황에 없는 필요 발주 후보 {len(required_order_items)}건")
        for required in required_order_items[:10]:
            lines.append(
                "- "
                f"{required.item_name}({required.item_code}) / "
                f"견적서 {required.quotation_no} / "
                f"거래처 {required.customer_name or '-'} / "
                f"단가 {format_number(required.unit_price)}원"
            )
            document = session.get(QuotationDocument, required.quotation_document_id)
            citation = row_citation(
                document.source_filename if document else None,
                document.source_sheet_name if document else None,
                None,
            )
            sources.append(
                source_dict(
                    source_type="quotation_required_order",
                    filename=document.source_filename if document else None,
                    citation=citation,
                    document_id=required.quotation_document_id,
                    text=(
                        f"견적서번호={required.quotation_no}, 품목명={required.item_name}, "
                        f"품목코드={required.item_code}, 거래처={required.customer_name}, "
                        f"단가={required.unit_price}"
                    ),
                )
            )

    lines.append("")
    lines.append("출처:")
    lines.extend(f"- {source['citation']}" for source in sources[:12])

    return HandlerResult(answer="\n".join(lines), sources=sources[:12])
